(define (problem example)
    (:domain SETCOVER)
    (:objects s1 s2 s3 s4 s5 - set 
              e1 e2 e3 e4 - elem)
    (:init
        (not (covered e1))
        (not (covered e2))
        (not (covered e3))
        (not (covered e4))
        (contains s1 e1)
        (contains s2 e2)
        (contains s2 e3)
        (contains s3 e4)
        (contains s4 e1)
        (contains s4 e2)
        (contains s5 e3)
        (contains s5 e4)
    )
    (:goal (and
            (covered e1) 
            (Covered e2) 
            (covered e3) 
            (covered e4)
        )
    )
)
